### ISSUE TITLE
feature if possible

### ISSUE THREAD

**Issue by valantislevas** [laterbreh/steam-friend-advertiser#1]
Is possible to send mass message to all of my steam friends that is member in my specific steam group?

**Comment by laterbreh** [comment]
Sorry for the late response! I have more or less abandoned this project. There is a way to send a broadcast to all members of a steam group built into steam. Not as a message though. 

I'll be looking into possibly re-writing this with possible extra features soon, I didn't realize there was a demand still for this little script!
