### ISSUE TITLE
Where do I put the info in user and pass?

### ISSUE THREAD

**Issue by RealBrianOG** [laterbreh/steam-friend-advertiser#2]
I Don't know where it has like 5 spots to put it in,

**Comment by andrewda** [comment]
Read the README. It's very clear on how to run the bot.

1. `npm install`
2. `node bot.js`
3. Enter your username and password when prompted
4. Enter message

**Comment by RealBrianOG** [comment]
But where do I type those commands.

**Comment by andrewda** [comment]
If you're running Windows, use `cmd` or `Powershell`. If you're using macOS or Linux, use `Terminal`.
